eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2012/eureka/
spring:
  application:
    name: twm-mkt-service

server:
  port: 40037

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #milliseconds
        readTimeout: 10000